### ISSUE TITLE
Нету скомпилированной версии в репозитории.

### ISSUE THREAD

**Issue by Pinegin** [raidan00/vue-r-mask#4]
Привет.

Обратил внимание на автора в package. Надеюсь почта на mail.ru говорит о том что меня тут поймут и на русском языке.

Понравился твой скрипт, простой и понятные. Но возникает с ним проблема. При попадании в билд он не компилируется, так как стоит запрет на компиляцию в папке node_modules.

Можно включить скомпилированную версию в модуль?

**Comment by raidan00** [comment]
Не совсем понимаю о чем идет речь. Поскольку у меня при билде webpack минифицирует JS нормально.

**Comment by raidan00** [comment]
"стоит запрет на компиляцию в папке node_modules" где он установлен?

**Comment by Pinegin** [comment]
Привет установке модуля, есть только index.js и caretPos.js
Больше никаких файлов нету. Я подключаю его в мой проект на NUXT и при сборке в мой билд попадает ваш модуль как он есть. То есть мой сборщик его не компилит под старые версии браузеров.

**Comment by raidan00** [comment]
В других модулях vue.js тоже нет "компилированных" файлов. "Компиляция" происходид на стадии сборки вашего проекта. Только вы занете под какие версии браузеров бабелю нужно модифицировать js и после его минифицировать. Попробуйте настроить вас сборщик, поскольку у меня в проекте все "компилируется" нопмально.
