### ISSUE TITLE
vue-r-mask did not work with Vuetify text field

### ISSUE THREAD

**Issue by viralprajapati94** [raidan00/vue-r-mask#8]
Hello,

I'm trying implement masking with v-text-field of vuetify Js but did not work.

It is work well in Input Type as below
`<input name="name" v-model="masked_value" v-mask="pattern"  placeholder="Choose email">`

I'm trying below code with vuetify its not working.
```
<v-text-field
        name="name"
        v-model="masked_value"
        :label="label"
        :placeholder="placeholder"
        outlined
        dense
        hide-details="auto"
        :class="classes"
        v-mask="pattern"
      >
      </v-text-field>
```
Please give me any solutions.

**Comment by raidan00** [comment]
vue-r-mask works only with native html tags. If you want attach vue-r-mask to wrapper around native input you need event propagation to that wrapper.
